### ISSUE TITLE
Internet connection problems with Brittney

### ISSUE THREAD

**Issue by ryshoooo** [computerskole/cvr#12]

**Comment by Dennis87DK** [comment]
i will ensure a new router, also might need to plan some short shotdowns/restarts to ensure everything always run the best.

**Comment by ryshoooo** [comment]
Scheduled maintenance already, good stuff! :)

**Comment by Dennis87DK** [comment]
Unfurtunely the router was not collected today, will be collected tomorrow to ensure the best week performens for Brittney
