### ISSUE TITLE
# Delivery on data - EAVærktøj

### ISSUE THREAD

**Issue by Dennis87DK** [computerskole/cvr#18]
Can we add the 3 branches and give the file all of Sjælland. this is to ensure we have an good ambassador on the data. Michael Bjerg my body with good connections. This data will also be used as samples for new protential customers

**Comment by ryshoooo** [comment]
Couple of complementary questions:

- Which data product is this in regards to? DP.001 or DP.001.00?
- What is the complete list of requirements for this data product? (i.e. active only? which branches? reklamebeskyttet? etc.)
- Is this going to be a scheduled or one time delivery?
- What output data format is required?

**Comment by ryshoooo** [comment]
Based on the conversation, the requirements are as followed:
- Based on DP.001
- Status: [Aktiv, NORMAL]
- Post number: [1000, 3700), [4000, 5000) (Sjaelland)
- Branchecodes: 433200, 433410, 432200, 439910, 432100, 439990, 439100, 412000, 433900, 433300, 432900, 683210, 682040, 682010, 256200, 251100, 952900
- Reklamebeskyttet: False
- AntalAnsatteInklusivEjere 2 <= x <= 19
- One-shot only
- CSV for the one-shot

**Comment by Dennis87DK** [comment]
Yes, this is correct.
